name: Build and Deploy
defaults:
  run:
    working-directory: webapp

permissions:
  contents: write
on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          repository: OpenBimRL/OpenBimRL-CreatorTool
          path: .
          set-safe-directory: true


      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm ci
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: webapp/dist # The folder the action should deploy.
          repository-name: OpenBimRL/OpenBimRL-CreatorTool
          token: ${{ secrets.GITHUB_TOKEN }}
