name: Create new Release
run-name: ${{ github.actor }} created a new release
on:
  push:
    branches:
      - master

jobs:
  create_release:
    defaults:
        run:
            shell: bash
            working-directory: webapp

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - run: npm version patch

      - name: Set version env
        id: set_version_env
        run: |
          echo "VERSION=$(npm pkg get version)" >> $GITHUB_ENV

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create "$env.VERSION"
