name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches:
      - master

jobs:
  create_release_branch:
    defaults:
        run:
            shell: bash
            working-directory: scripts

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create Release
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - run: npm version patch
      - name: Set verion env
        id: set_version_env
        run: |
          echo "VERSION=$(npm pkg get version)" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: ${{ env.VERSION }}
