name: Create new Release
run-name: ${{ github.actor }} created a new release
on:
  push:
    branches:
      - master

jobs:
  create_release:
    defaults:
        run:
            shell: bash
            working-directory: webapp

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      
      - name: build app
        run: npm run build

      - name: zip build
        run: zip -r build.zip dist

      - name: Create npm patch
        id: create_npm_patch
        run: |
          echo "VERSION=$(npm version patch)" >> "$GITHUB_OUTPUT"

      - run: echo "${{ steps.create_npm_patch.outputs.VERSION  }}"

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create ${{ steps.create_npm_patch.outputs.VERSION }} ./build.zip
